#!/bin/bash

if [ $# == 1 ]
then
  if [ "$1" == "clean" ]
  then
    rm -f *.o
	  rm calcServer
  else
    echo "usage: ./make or ./make clean or ./make <driver number>"
  fi
else
  gcc -Wall -g -std=gnu99 -o calcServer calcServer.c -lpthread
  if [ $? == 0 ]
  then
    echo "Compile successful"
  else
    echo "Compile error"
  fi
fi
